name: google_contacts
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.11
  connectivity_plus: ^6.1.4
  country_code_picker: ^3.3.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^3.15.1
  flutter_dotenv: ^5.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  lottie: ^3.3.1
  path: ^1.9.1
  permission_handler: ^12.0.1
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/illustrations/
    - assets/lottie/